### ISSUE TITLE
Getting Couldnt read file: open key.enc: no such file or directory while running for AWS KMS

### ISSUE THREAD

**Issue by pavanreddy07385** [bruj0/vault-recovery-key#13]
can u pls help us resolve this issue?

 ./vault-recovery-key  -enc-key key.enc -env awskms -shamir-shares 5 -shamir-threshold 3
INFO[0000] Starting version 0.2                         
INFO[0000] Starting with environment awskms             
FATA[0000] Couldnt read file: open key.enc: no such file or directory 

where do we get this key.enc from?

**Comment by jdfriedma** [comment]
@pavanreddy07385 you generate that key by running the operations [in this section](https://github.com/bruj0/vault-recovery-key#encrypted-recovery-keys-dump) against the relevant storage entries. Give that a shot and see if that works for you.
